{{- $fullName := include "acend-hugo-template.fullname" . -}}
{{- $svcPort := .Values.acendTraining.servicePort -}}
{{- $releaseName := .Release.Name -}}
{{- $all := . -}}
{{- range .Values.acendTraining.deployments }}
{{- $hostname := "" }}
{{- if or (eq $releaseName "main") (eq $releaseName "latest") }}
{{- $hostname = printf "%s%s%s" .ingress.appname "." .ingress.domain }}
{{- else }}
{{- $hostname = printf "%s%s%s%s%s" .ingress.appname "-" $releaseName "." .ingress.domain }}
{{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "acend-hugo-template.labels" $all | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-hugo-template.name" $all }}-{{ .name }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - "{{ $hostname }}"
      secretName: {{ $hostname | replace "." "-" }}
  rules:
    - host: "{{ $hostname }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-{{ .name }}
              servicePort: {{ $svcPort }}
{{- end }}